name: date_reminder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_bottom_navigation_bar: ^0.2.0
  cupertino_icons: ^0.1.3
  devicelocale: ^0.3.3
  firebase_admob: ^0.10.2
  flutter_countdown_timer: ^1.5.0
  flutter_holo_date_picker: ^0.2.3
  flutter_icons: ^1.1.0
  flutter_local_notifications: ^3.0.1+6
  flutter_multi_formatter: ^1.3.0
  flutter_open_whatsapp: ^0.1.2
  flutter_screenutil: ^3.2.0
  fluttercontactpicker: ^3.1.0
  path: ^1.7.0
  path_provider: ^1.6.24
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.12+4
  smart_select: ^4.3.2
  sqflite: ^1.3.2+1
  syncfusion_flutter_calendar: ^18.3.53
  url_launcher: ^5.7.10
  workmanager: ^0.2.3


  device_preview: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/onboarding_assets/
    - assets/images/
    - json/
    - lang/en.json
    - lang/tr.json
    - lang/ru.json

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Medium.ttf
          style: normal
